'use client';

import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Building2, CheckCircle2, CircleDollarSign, CreditCard, Plus, Search, Users } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import api from '@/lib/api';
import { DashboardShell, formatCurrency, formatDate, QueryState, StatCard, StatusBadge } from '@/components/dashboard-ui';

type Organization = { _id: string; name: string; status: string; createdAt: string };
type Plan = { _id: string; name: string; price: number; billingInterval: 'MONTHLY' | 'YEARLY'; features: string[]; isActive: boolean };
type Subscription = { _id: string; organizationId: string; planId: string; status: string };
type Transaction = { _id: string; organizationId: string; amount: number; currency: string; status: string; createdAt: string };

export default function PlatformAdminDashboard() {
  const { user, logout, loading } = useAuth();
  const router = useRouter();
  const queryClient = useQueryClient();
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [transactionStatus, setTransactionStatus] = useState('');
  const [editingPlan, setEditingPlan] = useState<Plan | null>(null);
  const [planForm, setPlanForm] = useState({ name: '', price: '', billingInterval: 'MONTHLY', features: '' });

  useEffect(() => { if (!loading && (!user || user.role !== 'PLATFORM_ADMIN')) router.replace('/login'); }, [loading, router, user]);
  const organizations = useQuery({ queryKey: ['organizations', search, status], queryFn: async () => (await api.get<{ organizations: Organization[] }>('/organizations', { params: { search: search || undefined, status: status || undefined } })).data.organizations, enabled: user?.role === 'PLATFORM_ADMIN' });
  const plans = useQuery({ queryKey: ['plans'], queryFn: async () => (await api.get<{ plans: Plan[] }>('/plans')).data.plans, enabled: user?.role === 'PLATFORM_ADMIN' });
  const subscriptions = useQuery({ queryKey: ['subscriptions'], queryFn: async () => (await api.get<{ subscriptions: Subscription[] }>('/subscriptions/all')).data.subscriptions, enabled: user?.role === 'PLATFORM_ADMIN' });
  const transactions = useQuery({ queryKey: ['transactions', transactionStatus], queryFn: async () => (await api.get<{ transactions: Transaction[] }>('/transactions/all', { params: { status: transactionStatus || undefined } })).data.transactions, enabled: user?.role === 'PLATFORM_ADMIN' });
  const memberCounts = useQuery({ queryKey: ['organization-member-counts', organizations.data?.map((org) => org._id).join(',')], queryFn: async () => Object.fromEntries(await Promise.all((organizations.data || []).map(async (organization) => [organization._id, (await api.get<{ count: number }>(`/organizations/${organization._id}/members`)).data.count]))), enabled: Boolean(organizations.data?.length) });
  const invalidate = () => { queryClient.invalidateQueries({ queryKey: ['organizations'] }); queryClient.invalidateQueries({ queryKey: ['plans'] }); queryClient.invalidateQueries({ queryKey: ['subscriptions'] }); queryClient.invalidateQueries({ queryKey: ['transactions'] }); };
  const organizationAction = useMutation({ mutationFn: async ({ id, action }: { id: string; action: 'suspend' | 'reactivate' }) => api.post(`/organizations/${id}/${action}`), onSuccess: invalidate });
  const planAction = useMutation({ mutationFn: async (data: { id?: string; payload: typeof planForm }) => { const payload = { name: data.payload.name, price: Number(data.payload.price), billingInterval: data.payload.billingInterval, features: data.payload.features.split(',').map((item) => item.trim()).filter(Boolean) }; return data.id ? api.put(`/plans/${data.id}`, payload) : api.post('/plans', payload); }, onSuccess: () => { setEditingPlan(null); setPlanForm({ name: '', price: '', billingInterval: 'MONTHLY', features: '' }); invalidate(); } });
  const togglePlan = useMutation({ mutationFn: async (plan: Plan) => api.post(`/plans/${plan._id}/${plan.isActive ? 'disable' : 'enable'}`), onSuccess: invalidate });
  const overview = useMemo(() => ({ revenue: (transactions.data || []).filter((item) => item.status === 'SUCCESS').reduce((total, item) => total + item.amount, 0), totalUsers: (Object.values(memberCounts.data || {}) as number[]).reduce((total, count) => total + count, 0), activeSubscriptions: (subscriptions.data || []).filter((item) => item.status === 'ACTIVE').length, failedPayments: (transactions.data || []).filter((item) => item.status === 'FAILED').length }), [memberCounts.data, subscriptions.data, transactions.data]);
  if (!user) return null;

  return <DashboardShell title="Platform control center" subtitle="Monitor every organization, plan, and transaction from one secure workspace." email={user.email} onLogout={() => { logout(); router.replace('/login'); }}>
    <QueryState loading={organizations.isLoading || plans.isLoading || subscriptions.isLoading || transactions.isLoading} error={organizations.error || plans.error || subscriptions.error || transactions.error}>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Organizations" value={organizations.data?.length ?? 0} icon={<Building2 size={21} />} detail="Matching current filters" /><StatCard label="Total users" value={overview.totalUsers} icon={<Users size={21} />} /><StatCard label="Active subscriptions" value={overview.activeSubscriptions} icon={<CheckCircle2 size={21} />} /><StatCard label="Recorded revenue" value={formatCurrency(overview.revenue)} icon={<CircleDollarSign size={21} />} /><StatCard label="Failed payments" value={overview.failedPayments} icon={<CreditCard size={21} />} /></div>
      <section className="mt-7 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 p-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-bold text-slate-950">Organizations</h2><p className="mt-1 text-sm text-slate-500">Search and control tenant access.</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 text-slate-400" size={17} /><input aria-label="Search organizations" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search organizations" className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none ring-indigo-500 focus:ring-2 sm:w-56" /></label><select aria-label="Filter organization status" value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><option value="">All statuses</option><option>ACTIVE</option><option>TRIAL</option><option>SUSPENDED</option><option>CANCELLED</option></select></div></div>
        {!organizations.data?.length ? <p className="p-8 text-center text-sm text-slate-500">No organizations match the selected filters.</p> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Organization</th><th className="px-5 py-3">Plan</th><th className="px-5 py-3">Members</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Joined</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{organizations.data.map((organization) => { const subscription = subscriptions.data?.find((item) => item.organizationId === organization._id); const plan = plans.data?.find((item) => item._id === subscription?.planId); return <tr key={organization._id}><td className="px-5 py-4 font-semibold text-slate-900">{organization.name}</td><td className="px-5 py-4 text-slate-600">{plan?.name || 'No active plan'}</td><td className="px-5 py-4 text-slate-600">{memberCounts.data?.[organization._id] ?? '—'}</td><td className="px-5 py-4"><StatusBadge value={organization.status} /></td><td className="px-5 py-4 text-slate-600">{formatDate(organization.createdAt)}</td><td className="px-5 py-4 text-right">{organization.status === 'SUSPENDED' ? <button onClick={() => organizationAction.mutate({ id: organization._id, action: 'reactivate' })} className="font-semibold text-emerald-700 hover:text-emerald-900">Reactivate</button> : <button onClick={() => { if (window.confirm(`Suspend ${organization.name}? Members will lose access.`)) organizationAction.mutate({ id: organization._id, action: 'suspend' }); }} className="font-semibold text-rose-700 hover:text-rose-900">Suspend</button>}</td></tr>; })}</tbody></table></div>}</section>
      <div className="mt-7 grid gap-7 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Plan management</h2><p className="mt-1 text-sm text-slate-500">Create, update, and activate subscription plans.</p></div><Plus className="text-indigo-600" /></div><form onSubmit={(event) => { event.preventDefault(); planAction.mutate({ id: editingPlan?._id, payload: planForm }); }} className="mt-5 grid gap-3 sm:grid-cols-2"><input required placeholder="Plan name" value={planForm.name} onChange={(event) => setPlanForm({ ...planForm, name: event.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input required min="0" step="0.01" type="number" placeholder="Price (USD)" value={planForm.price} onChange={(event) => setPlanForm({ ...planForm, price: event.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><select value={planForm.billingInterval} onChange={(event) => setPlanForm({ ...planForm, billingInterval: event.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="MONTHLY">Monthly</option><option value="YEARLY">Yearly</option></select><input placeholder="Features, comma separated" value={planForm.features} onChange={(event) => setPlanForm({ ...planForm, features: event.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><div className="flex gap-2 sm:col-span-2"><button disabled={planAction.isPending} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700 disabled:opacity-50">{editingPlan ? 'Save changes' : 'Create plan'}</button>{editingPlan && <button type="button" onClick={() => { setEditingPlan(null); setPlanForm({ name: '', price: '', billingInterval: 'MONTHLY', features: '' }); }} className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">Cancel</button>}</div></form><div className="mt-5 divide-y divide-slate-100">{plans.data?.map((plan) => <div key={plan._id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-semibold">{plan.name} <span className="font-normal text-slate-500">· {formatCurrency(plan.price)}/{plan.billingInterval === 'MONTHLY' ? 'mo' : 'yr'}</span></p><p className="text-xs text-slate-500">{plan.features.join(' · ') || 'No features specified'}</p></div><div className="flex gap-3"><button onClick={() => { setEditingPlan(plan); setPlanForm({ name: plan.name, price: String(plan.price), billingInterval: plan.billingInterval, features: plan.features.join(', ') }); }} className="text-sm font-semibold text-indigo-700">Edit</button><button onClick={() => togglePlan.mutate(plan)} className="text-sm font-semibold text-slate-700">{plan.isActive ? 'Disable' : 'Enable'}</button></div></div>)}</div></section>
        <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><h2 className="font-bold">Platform transactions</h2><p className="mt-1 text-sm text-slate-500">Latest recorded payment activity.</p></div><select value={transactionStatus} onChange={(event) => setTransactionStatus(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><option value="">All statuses</option><option>SUCCESS</option><option>PENDING</option><option>FAILED</option><option>REFUNDED</option><option>ROLLED_BACK</option></select></div><div className="divide-y divide-slate-100">{transactions.data?.slice(0, 7).map((transaction) => <div key={transaction._id} className="flex items-center justify-between gap-4 p-4"><div><p className="font-semibold">{formatCurrency(transaction.amount, transaction.currency.toUpperCase())}</p><p className="mt-1 text-xs text-slate-500">{organizations.data?.find((org) => org._id === transaction.organizationId)?.name || 'Organization'} · {formatDate(transaction.createdAt)}</p></div><StatusBadge value={transaction.status} /></div>)}{!transactions.data?.length && <p className="p-8 text-center text-sm text-slate-500">No transactions have been recorded.</p>}</div></section></div>
    </QueryState>
  </DashboardShell>;
}
